[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/unite.vim'


[[plugins]]
repo = 'scrooloose/nerdtree'


[[plugins]]
repo = 'vim-airline/vim-airline'




#[[plugins]] # カラースキーマ
#repo = 'w0ng/vim-hybrid'
#hook_add = '''
#  set background=dark
#2	  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
#		  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
#			  au MyAutoCmd VimEnter * nested colorscheme hybrid
#				'''











