[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add ='''
	let g:jedi#use_tabs_not_buffers = 1 

	let g:jedi#popup_select_first = 0
	let g:jedi#popup_on_dot = 0 
	let g:jedi#goto_command = "<leader>d"
	let g:jedi#goto_assignments_command = "<leader>g"
	let g:jedi#goto_definitions_command = ""
	let g:jedi#documentation_command = "K"
	let g:jedi#usages_command = "<leader>n"
	let g:jedi#rename_command = "<leader>R" 
	autocmd FileType python setlocal completeopt-=preview 
'''

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'



[[plugins]]
repo = 'kevinw/pyflakes'
on_ft = 'python'


[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = 'python'
hook_add = '''
	let g:flake8_show_in_gutter = 1
	let g:flake8_show_in_file = 1
	
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']
hool_add ='''
	let g:previm_open_cmd = 'open -a Firefox'
'''


[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup   = 1
let g:deoplete#auto_complete_delay = 0
inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
				        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
								'''
								on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_i = 1
hook_source = '''
" Plugin key-mappings.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
"imap <C-k>     <Plug>(neosnippet_expand_or_jump)
"smap <C-k>     <Plug>(neosnippet_expand_or_jump)
"xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <expr><TAB>
 \ pumvisible() ? "\<C-n>" :
  \ neosnippet#expandable_or_jumpable() ?
	 \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

	 imap <expr><CR>
	 \ (pumvisible() && neosnippet#expandable()) ? "\<Plug>(neosnippet_expand_or_jump)" : "\<CR>"


	 smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	 \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

	 " For conceal markers.
	 "if has('conceal')
	 "  set conceallevel=2 concealcursor=niv
	 "endif
	 '''



[[plugins]]
repo = 'sudar/vim-arduino-syntax'
on_ft = ['arduino']


[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'Shougo/context_filetype.vim'


[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'


[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = 'python'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = [ 'css','html']

[[pllugins]]
repo = 'taichouchou2/surround.vim'
on_ft = [ 'css','html']
